// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptzwmmqjmhmzngzgaisa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0endtbXFqbWhtem5nemdhaXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MTM1MzUsImV4cCI6MjA2MjA4OTUzNX0.U4Cy6xIyru4aIqpz7tIrxsF3N0O_9B1Z2kJrZCu4j98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);